// assets.js - بانک عکس‌ها و گییف‌های سالم بازی

const photos = {
  // پادشاهان
  cyrus: "AgACAgQAAxkBAAEqCuxqH_gzDC0lhnhq5XY5trPLrtNiKAACiQ5rG4APAVESIQfjCtTuagEAAwIAA3kAAzsE",
  darius: "AgACAgQAAxkBAAEqCwxqH_vHXf_othfTA2jTsuAZqqbuSQACkg5rG4APAVFF2KiazmU2oQEAAwIAA3kAAzsE",
  anushirvan: "AgACAgQAAxkBAAEqCxBqH_xgAAGDky46hdN3TNPOpoLa7CAAApQOaxuADwFRz7glJ8phpNsBAAMCAAN5AAM7BA",
  shahabbas: "AgACAgQAAxkBAAEqC1ZqIAABw4hu6fz4rv1Sm5C2Wxg654IAApUOaxuADwFREeM5uPDykG0BAAMCAAN5AAM7BA",
  nader: "AgACAgQAAxkBAAEqC8BqIAqp_nwtXft1OGSIEp-AfmmTuwACpw5rG4APAVERR2QTdtSDlwEAAwIAA3kAAzsE",
  karim: "AgACAgQAAxkBAAEqDQpqICDyBdfDPIAlcnUqTvtg1bfXlwACyA5rG4APAVHI6esAAVBUeW0BAAMCAAN5AAM7BA",
  rezashah: "AgACAgQAAxkBAAEqDRRqICGe82zWxY2HygESUHruXYt-pwAC1w5rG4APAVEE1NreIhRuWQEAAwIAA3kAAzsE",
  mohammadreza: "AgACAgQAAxkBAAEqDSBqICI_SreoP_nMRvgKJ_MB9q4CnQAC2A5rG4APAVHq3LzEIHc2lwEAAwIAA3kAAzsE",
  khomeini: "AgACAgQAAxkBAAEqDSVqICKpjXkKp6VNQ5cFJXfaBxJ6SQAC2Q5rG4APAVFwaaT8pT6IowEAAwIAA3cAAzsE",
  khamenei: "AgACAgQAAxkBAAEqDSpqICL4y8wH9x-j28C2AAFizyn8n7AAAtoOaxuADwFRayCfRQAB1p5AAQADAgADdwADOwQ",
  
  // ملکه‌ها
  atousa: "AgACAgQAAxkBAAEqF_VqIUiXDNrgihg0fmG12Gs01PrJ8QACxA1rG_JGCVFD_JpmxUMtsgEAAwIAA3kAAzsE",
  kasandan: "AgACAgQAAxkBAAEqF_ZqIUiXmwzuK0xxiuZqsSA9keytaAACxQ1rG_JGCVENMXkMV5UfAQEAAwIAA3kAAzsE",
  parmis: "AgACAgQAAxkBAAEqF_dqIUiXZp0UrzV7tpEwjxIHJwL0ZwACxg1rG_JGCVEm2_xq5oJQjwEAAwIAA3gAAzsE",
  artunis: "AgACAgQAAxkBAAEqF_lqIUiXoX-Xe4NVgsZbLXA7KmRQtgACxw1rG_JGCVEigD-9RqTJpgEAAwIAA3kAAzsE",
  shirin: "AgACAgQAAxkBAAEqF_pqIUiX5hgu2spv5cqpQNhwkzoZWQACyA1rG_JGCVFjP_brzFcJeAEAAwIAA3kAAzsE",
  malek_jahan: "AgACAgQAAxkBAAEqF_xqIUiXpjy1R-LudoyFGrJD2qEu3QACyg1rG_JGCVGeTGCNTHEaQQEAAwIAA3kAAzsE",
  taj_olmoluk: "AgACAgQAAxkBAAEqF_5qIUiXE2lOOvP0_IkqR5oCoPpBhAACyw1rG_JGCVHtjb_Kyi9t2AEAAwIAA3kAAzsE",
  esmat: "AgACAgQAAxkBAAEqGAABaiFIl4W-9FJFZnQ4C2lkvXQnxmEAAs0NaxvyRglRrLHcR39hxqUBAAMCAAN5AAM7BA",
  khadijeh: "AgACAgQAAxkBAAEqGAJqIUiXDDIfX1SQmNRuQnojI3TFzgACzg1rG_JGCVFOZ9bATwodkAEAAwIAA3kAAzsE",
  mansoureh: "AgACAgQAAxkBAAEqGANqIUiXm9OB_AYLRM7ZqoWuB9_ykwAC0g1rG_JGCVF5zXNH_Dm_ewEAAwIAA3gAAzsE",
  
  // زنان جنگجو
  gordafarid: "AgACAgQAAxkBAAEqF6ZqIUGvhScsO4blT-CbwAVlN5CW2gACnA1rG_JGCVGyVXBSWWREhwEAAwIAA3kAAzsE",
  artemis: "AgACAgQAAxkBAAEqF6VqIUGvLWKsCa-lTLMvGzPDuoBUmgACmw1rG_JGCVFYnmKwrGD4vAEAAwIAA3kAAzsE",
  bouran: "AgACAgQAAxkBAAEqF6RqIUGvMJBx5IvNRofoZ8LIjEUQhgAClw1rG_JGCVEigufPgWVG4QEAAwIAA3kAAzsE",
  homay: "AgACAgQAAxkBAAEqF6dqIUGvQR6I1D5rIDBzEc_D1Im-rQACnQ1rG_JGCVH-XHKbJOZwzwEAAwIAA3kAAzsE",
  
  // شخصیت‌های دیگر
  persian_queen: "AgACAgQAAxkBAAEqF6lqIUGv10Tu1XXOsio5fGJ4kuFDtwACnw1rG_JGCVHj684FORlTOwEAAwIAA3kAAzsE",
  mahd_olya: "AgACAgQAAxkBAAEqF6pqIUGvvAABUx6U9AS7UUF1q0Uu0E0AAqANaxvyRglRpy5Msbn1-SMBAAMCAAN5AAM7BA",
  reza_kabir: "AgACAgQAAxkBAAEqDhxqIDAr_kFEEVk6PpR6-6MQ8xtobQAC_A5rG4APAVFXBwkTZaZBUgEAAwIAA3gAAzsE",
  soldier_iran_iraq: "AgACAgQAAxkBAAEqDiZqIDCc9bGzQWtIa_nd9kU4bYlLZAAC_g5rG4APAVFhExSQa7SOBAEAAwIAA3kAAzsE",
  commanders_islamic: "AgACAgQAAxkBAAEqEadqIHW0aO79nY9EHGvTVLckjvKAlwAC6w9rG4APAVEa86AZ5XmHMQEAAwIAA3kAAzsE",
  siraz: "AgACAgQAAxkBAAEqFodqISonjCvmbKmawsmFCzAV-A7hCwACdw1rG_JGCVHEOM2EpM4tHgEAAwIAA3kAAzsE",
  
  // متفرقه
  map_iran_ancient: "AgACAgQAAxkBAAEqEn1qIIS1Cpu26NucbgH1ankioQm-9AACHRBrG4APAVHcgdJ7gFsdyAEAAwIAA3gAAzsE",
  shir_khorshid: "AgACAgQAAxkBAAEqGVJqIV2gHEUpDQUUfck0hwgJx_QTjQACPxBrG4APAVGrcr1xhhY1AQEAAwIAA3gAAzsE",
  war_iran_iraq: "AgACAgQAAxkBAAEqDiZqIDCc9bGzQWtIa_nd9kU4bYlLZAAC_g5rG4APAVFhExSQa7SOBAEAAwIAA3kAAzsE",
  
  // موشک‌ها
  missile_fattah: "AgACAgQAAxkBAAEqGXlqIV2h7RfXckZup-Ha8vlUAAGS_o0AAu4NaxvyRglRBRlbMEyrx0QBAAMCAAN5AAM7BA",
  missile_khorramshahr: "AgACAgQAAxkBAAEqGXpqIV2hZ-cvrruLiDh0e7STIYck_QAC7w1rG_JGCVHQW9mL44xh9gEAAwIAA3gAAzsE",
  missile_emad: "AgACAgQAAxkBAAEqGXtqIV2hy_s3iKX_Hop76X_-gWPxswAC8A1rG_JGCVG0HRk0xqeRoAEAAwIAA3kAAzsE",
  
  // موجودات افسانه‌ای
  devil: "AgACAgQAAxkBAAEqGjBqIWRN4m9TIMsISLquTd6f05AwqQACFg5rG9cu8VA5kUT_RJVxWwEAAwIAA3kAAzsE",
  snake_king: "AgACAgQAAxkBAAEqGjFqIWRNCxh1-j1k-lJQtNqAGTop3AACFw5rG9cu8VDIa6hQ0ARWaQEAAwIAA3kAAzsE",
  um_al_jinni: "AgACAgQAAxkBAAEqGjVqIWRNa6NNNPA_W7iUJjAR3PUAAUAAAhkOaxvXLvFQ7I3gbmQTUL0BAAMCAAN5AAM7BA",
  mountain_dragon: "AgACAgQAAxkBAAEqGjZqIWRNe4Rmq4FSjQ7wdu22cfkwEQACHA5rG9cu8VBILeJFIlQ5kQEAAwIAA3kAAzsE",
  phoenix: "AgACAgQAAxkBAAEqGjNqIWRNIsQKOamq4k4eX8BP8LNqegACGA5rG9cu8VA167M5oqKbjwEAAwIAA3kAAzsE",
  
  // سلاح‌ها
  dagger: "AgACAgQAAxkBAAEqGjdqIWRNa9r2wExfUoeDAl9M9zJgvAACHw5rG9cu8VDMz1yDpuuBagEAAwIAA3kAAzsE",
  sword: "AgACAgQAAxkBAAEqGjhqIWRNXmPzB82LsD5xvQkAAfsEHP8AAiAOaxvXLvFQhNQt1fDaaBwBAAMCAAN5AAM7BA",
  bow: "AgACAgQAAxkBAAEqGjlqIWRN_W0AAS1cZ5FSHJsWMqu1GOYAAiEOaxvXLvFQz5eYDfG_HCsBAAMCAAN4AAM7BA",
  axe: "AgACAgQAAxkBAAEqGjpqIWRN876SySLLuGybhbtY0Qn1hAACIw5rG9cu8VCC1L_O6uURuQEAAwIAA3kAAzsE",
  spear: "AgACAgQAAxkBAAEqGjtqIWRN8D4hqODSK-Ask7eW6BGHyAACJA5rG9cu8VCSKKiSX1WdgwEAAwIAA3kAAzsE",
  dagger2: "AgACAgQAAxkBAAEqGjxqIWRN3i4WBmIcu565RiZo2iqnXgACJQ5rG9cu8VCOvr949hsezwEAAwIAA3kAAzsE",
  bow2: "AgACAgQAAxkBAAEqGj1qIWRNhV62FhYmpw9Ehsfd9wiNuwACJg5rG9cu8VAfhZuNjCCP9QEAAwIAA3kAAzsE",
  axe_upgraded: "AgACAgQAAxkBAAEqGj5qIWRNJU7kW0Np53vO9qwUfHd2DAACJw5rG9cu8VDgX8i8bKvapwEAAwIAA3kAAzsE",
  
  // زره‌ها
  wooden_shield: "AgACAgQAAxkBAAEqGj9qIWRN24mpOT4EXo85JOsWG_4oXgACKA5rG9cu8VC3XDPKERbnSwEAAwIAA3gAAzsE",
  leather_armor: "AgACAgQAAxkBAAEqGkBqIWRN9DraVQKb5bDX8yIg_IaTbAACKQ5rG9cu8VDoUz7bhZsp9wEAAwIAA3kAAzsE",
  golden_armor: "AgACAgQAAxkBAAEqGkFqIWRNzAfpbRhmjJnnGUWqERJrgAACKw5rG9cu8VBY1M7y2fKW-QEAAwIAA3kAAzsE",
  iron_armor: "AgACAgQAAxkBAAEqGkJqIWRNIoY-Ihl8sf3ZnneFW-mwowACLA5rG9cu8VACPZe64yeL3gEAAwIAA3kAAzsE",
  dragon_armor: "AgACAgQAAxkBAAEqGkNqIWRNoq5PaOKp1XA5gPQ6wD-AlQACLQ5rG9cu8VBBpjFoKUlNagEAAwIAA3kAAzsE",
  
  // غذاها
  bread: "AgACAgQAAxkBAAEqGkRqIWRNjk3PYW8Vr5EOMywo7LBtNgACLg5rG9cu8VC4UQ7khx5hZgEAAwIAA3gAAzsE",
  kebab: "AgACAgQAAxkBAAEqGkVqIWRNKQcNmYKZkZW28-BjraaBbgACLw5rG9cu8VCTGxXMyECjdAEAAwIAA3gAAzsE",
  chicken_kebab: "AgACAgQAAxkBAAEqGkdqIWRNMSbB27hetvqG0GfnBVed9wACMQ5rG9cu8VBH9qkPer-ATAEAAwIAA3gAAzsE",
  gheymeh: "AgACAgQAAxkBAAEqGkhqIWRN9zfTFZb34UK19qWq3230qgACMg5rG9cu8VCanlTgXyHErQEAAwIAA3kAAzsE",
  aash: "AgACAgQAAxkBAAEqGklqIWRNw-LVbRlGIkrISG9f5pfPKQACMw5rG9cu8VCzAoPV2QnjtwEAAwIAA3gAAzsE",
  
  // محیط
  forest: "AgACAgQAAxkBAAEqGthqIWVzMwfaxnI-B5rOjcwXbjIQuQACWw5rG9cu8VCdHd1QnlSBAAEBAAMCAAN5AAM7BA",
  mountain: "AgACAgQAAxkBAAEqGtlqIWVzEDs2E_WhvxarX5gOKBdDagACXA5rG9cu8VCBMGOJX1_gUQEAAwIAA3kAAzsE",
  mine: "AgACAgQAAxkBAAEqGtpqIWVznlccktins9ewC4TMO_5_JwACXQ5rG9cu8VAGiO__vqKaNQEAAwIAA3kAAzsE",
  desert: "AgACAgQAAxkBAAEqGuBqIWWBKUKmhBTxIogigcacwBAcqAACWg5rG9cu8VDH39IGzx7XDgEAAwIAA3gAAzsE",
  bazaar: "AgACAgQAAxkBAAEqGtxqIWVz1IB6e_bilpzNtktK9IEntgACYQ5rG9cu8VAVr24v9PDF5QEAAwIAA3gAAzsE",
};

const gifs = {
  nuclear_gif: "CgACAgQAAxkBAAEqEo9qIIXeZFa4e4pPIR67chxvh9D2XwACbwMAAlhtBFOyrDZljZRTyjsE",
  gladiator_fight: "CgACAgQAAxkBAAEqGVBqIV2gqODeVyqJ0O_R9cB9o7VgGgAC5AcAAiE7PVC7dRhONkLo3zsE",
  gladiator_win: "CgACAgQAAxkBAAEqGVFqIV2gfrxazteWVHN08BObPyakpgACAwMAAsmSjFPUScicY8iOhzsE",
};

module.exports = { photos, gifs };